[package]
name = "kucoin_arbitrage"
version = "0.0.2"
edition = "2021"
authors = ["Sho Kaneko <kanekoshoyu@gmail.com>"]
description = "Kucoin Arbitrage Framework in Async Rust"
repository = "https://github.com/kanekoshoyu/kucoin_arbitrage"
license = "MIT"


[dependencies]
kucoin_rs = "0.4.4"
log = "0.4"
chrono = "0.4"
env_logger = "0.9.1"
rust-ini = "0.18"
lazy_static = "1.4"
futures= "0.3"